version: '3'
services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - TZ=JST-9
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    volumes:
      - ./data:/opt/jboss/keycloak/standalone/data
      - ./application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore
