# LOG CONFIGURATION
logging:
    pattern:
        console: "%d{yyyy-MM-dd-HH:mm:ss.SSS} [%-5level] %logger - %msg%n"
    level:
        root: WARN
        cherry:
            oauth2app: DEBUG
        org:
            springframework: INFO
server:
    port: 8081
spring:
    main:
        banner-mode: off
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: https://localhost:8443/auth/realms/mydemo/protocol/openid-connect/certs
                    issuer-uri: https://localhost:8443/auth/realms/mydemo
